# Generated by Django 5.1.7 on 2025-07-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DShop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_id',
            field=models.TextField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='sub_type',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='type',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
