# Generated by Django 5.1.7 on 2025-07-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DShop', '0002_products_brand_products_product_id_products_sub_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bussiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bussiness_name', models.TextField(max_length=40)),
                ('bussiness_email', models.TextField(max_length=40)),
                ('password', models.TextField(max_length=16)),
                ('Address', models.TextField(max_length=100, null=True)),
                ('phone_no', models.TextField(max_length=10, null=True)),
                ('owner_name', models.TextField(max_length=50, null=True)),
                ('products', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=40)),
                ('email', models.TextField(max_length=40)),
                ('password', models.TextField(max_length=16)),
                ('Address', models.TextField(max_length=100, null=True)),
                ('phone_no', models.TextField(max_length=10, null=True)),
                ('customer_name', models.TextField(max_length=50, null=True)),
                ('cart', models.JSONField(blank=True, default=list)),
                ('order', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.RenameField(
            model_name='products',
            old_name='type',
            new_name='product_type',
        ),
    ]
