# Generated by Django 5.1.7 on 2025-09-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DShop', '0004_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='no_of_products',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
