# Generated by Django 5.1.7 on 2025-09-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DShop', '0005_products_no_of_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='no_of_products',
        ),
        migrations.AddField(
            model_name='bussiness',
            name='no_of_products',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
