# Generated by Django 5.1.7 on 2025-09-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DShop', '0006_remove_products_no_of_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.TextField(default='0', max_length=4, null=True),
        ),
    ]
