# Generated by Django 5.1.7 on 2025-09-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DShop', '0007_products_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='order_quantity',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
