# Generated by Django 5.1.7 on 2025-09-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DShop', '0008_products_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='alternate_email',
            field=models.TextField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='alternate_no',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
