# Generated by Django 5.1.7 on 2025-09-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DShop', '0009_customers_alternate_email_customers_alternate_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='order',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
