# Generated by Django 5.1.7 on 2025-09-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DShop', '0010_alter_customers_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='gifts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
