# Generated by Django 5.1.7 on 2025-09-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DShop', '0011_customers_gifts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer_Gifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OfferID', models.TextField(max_length=20, null=True)),
                ('name', models.TextField(max_length=50, null=True)),
                ('details', models.TextField(max_length=200, null=True)),
                ('discount_amount', models.TextField(max_length=10, null=True)),
                ('condition', models.TextField(max_length=50, null=True)),
            ],
        ),
    ]
