# Generated by Django 5.1.7 on 2025-10-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DShop', '0012_offer_gifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='average_rating',
            field=models.TextField(max_length=4, null=True),
        ),
    ]
