# Generated by Django 5.1.7 on 2025-10-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DShop', '0013_products_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='people_buy',
            field=models.TextField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='products',
            name='people_rate',
            field=models.TextField(default='0', max_length=10),
        ),
    ]
