# Generated by Django 5.1.7 on 2025-10-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DShop', '0014_products_people_buy_products_people_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='new_order',
            field=models.TextField(default='0', max_length=3),
        ),
    ]
