# Generated by Django 5.1.7 on 2025-10-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DShop', '0015_products_new_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='feedback_rating',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='products',
            name='ratings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
