# Generated by Django 5.1.7 on 2025-10-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DShop', '0016_products_feedback_rating_products_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='order',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
