# Generated by Django 5.1.7 on 2025-10-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DShop', '0017_alter_customers_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussiness',
            name='Address',
            field=models.TextField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bussiness',
            name='owner_name',
            field=models.TextField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bussiness',
            name='phone_no',
            field=models.TextField(default='', max_length=10, null=True),
        ),
    ]
